// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvs(arg1) {
  return window['go']['main']['App']['GetEnvs'](arg1);
}

export function SelectOutput() {
  return window['go']['main']['App']['SelectOutput']();
}

export function SelectProject() {
  return window['go']['main']['App']['SelectProject']();
}
