// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Extract(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetEnvs(arg1:string):Promise<Array<string>>;

export function SelectOutput():Promise<string>;

export function SelectProject():Promise<string>;
