// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvs(arg1:string):Promise<Array<string>>;

export function SelectOutput():Promise<string>;

export function SelectProject():Promise<string>;
